// this is very tedious, basically we need to transpile everything we import
// and use via jest that uses either ES modules or TypeScript
const ESM_IMPORTS = [
  "bail",
  "ccount",
  "character-entities",
  "comma-separated-tokens",
  "decode-named-character-reference",
  "fault",
  "hast-util-is-element",
  "hast-util-to-html",
  "hast-util-whitespace",
  "html-void-elements",
  "is-plain-obj",
  "micromark",
  "mdast-util-definitions",
  "mdast-util-frontmatter",
  "mdast-util-to-hast",
  "mdast-util-from-markdown",
  "mdast-util-to-string",
  "parse-entities",
  "property-information",
  "rehype-stringify",
  "remark-frontmatter",
  "remark-rehype",
  "remark-parse",
  "space-separated-tokens",
  "stringify-entities",
  "trough",
  "unified",
  "unist-builder",
  "unist-util-generated",
  "unist-util-position",
  "unist-util-visit",
  "unist-util-is",
  "unist-util-stringify-position",
  "vfile",
  "vfile-message",
];

module.exports = {
  automock: false,
  setupFiles: ["./test/setupJest.js"],
  transformIgnorePatterns: [`node_modules/.pnpm/(?!${ESM_IMPORTS.join("|")})`],
};
